apiVersion: v1
kind: ConfigMap
metadata:
  name: ${VM_NAME}-virtspec
  namespace: vms
data:
  virtSpec: |
    template:
      spec:
        domain:
          devices:
            disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
        volumes:
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: ${OS_USER}
              password: ${OS_PASSWORD}
              chpasswd: { expire: False }
              ssh_pwauth: True
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: ${VM_NAME}
  namespace: vms
  annotations:
    vm.cluster.gke.io/virt-spec-configmap: ${VM_NAME}-virtspec
spec:
  osType: ${OS_TYPE}
  compute:
    cpu:
      vcpus: ${CPU_CORES}
    memory:
      capacity: ${RAM_GB}Gi
  disks:
  - boot: true
    driver: virtio
    virtualMachineDiskName: ${VM_NAME}-boot
    autoDelete: false
  interfaces:
  - default: true
    name: eth0
    networkName: pod-network
---
apiVersion: v1
kind: Service
metadata:
  name: ${VM_NAME}-loadbalancer
  namespace: vms
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt/vm: ${VM_NAME}
