apiVersion: v1
kind: ConfigMap
metadata:
  name: rocky-virtspec
  namespace: vms
data:
  virtSpec: |
    template:
      spec:
        domain:
          devices:
            disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
        volumes:
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: rocky
              password: password123
              chpasswd: { expire: False }
              ssh_pwauth: True
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: rocky
  namespace: vms
  annotations:
    vm.cluster.gke.io/virt-spec-configmap: rocky-virtspec
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  disks:
  - boot: true
    driver: virtio
    virtualMachineDiskName: rocky-boot
    autoDelete: false
  interfaces:
  - default: true
    name: eth0
    networkName: pod-network
---
apiVersion: v1
kind: Service
metadata:
  name: rocky-loadbalancer
  namespace: vms
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    kubevirt/vm: rocky
